import * as React from 'react';
import Box from '@mui/material/Box';import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "./Component/Navbar.js";
import TextField from "@mui/material/TextField";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Navbar />

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
          {/* <TextField
            id="outlined-multiline-flexible"
            label="Multiline"
            multiline
            sx={{
              width: "600px",
              height: "1244",
            }}
            maxRows={12}
          /> */}
          <Box
            component="form"
            sx={{
              "& .MuiTextField-root": { m: 1, width: "25ch" },
            }}
            noValidate
            autoComplete="off"
          >
            <TextField
              id="outlined-multiline-static"
              label="Multiline"
              style = {{width: 850}}
              multiline
              rows={14}
              defaultValue="Default Value"
              fullWidth
            />
          </Box>
        </div>
      </main>
    </>
  );
}
